version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pharmacy_db
      MYSQL_USER: pharmacy_user
      MYSQL_PASSWORD: pharmacy_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      PMA_PORT: 3306
    ports:
      - "8080:80"
    volumes:
      - phpmyadmin_data:/etc/phpmyadmin
    depends_on:
      - mysql

volumes:
  mysql_data:
  phpmyadmin_data:
